export const GET_SLIDESHOW_DATA_REQUEST = "GET_SLIDESHOW_DATA_REQUEST";
export const GET_USER_DATA_RESPONSE = "GET_USER_DATA_RESPONSE";
//product
export const GET_PRODUCT_DATA_REQUEST= "GET_PRODUCT_DATA_REQUEST"
export const GET_PRODUCT_DATA_RESPONSE = "GET_PRODUCT_DATA_RESPONSE";
// /////////////////////////////////////////////////////////////////////////////////////
export const GET_DISCOUNT_DATA_REQUEST= "GET_DISCOUNT_DATA_REQUEST"
export const GET_DISCOUNT_DATA_RESPONSE = "GET_DISCOUNT_DATA_RESPONSE";
//article
export const GET_ARTICLE_DATA_REQUEST = "GET_ARTICLE_DATA_REQUEST";
///////////////////////////////////////////////////////////////////////////////
export const GET_ARTICLE_DATA_RESPONSE = "GET_ARTICLE_DATA_RESPONSE";
export const EDIT_SLIDESHOW_REQUEST="EDIT_SLIDESHOW_REQUEST";
export const UPLOAD_REQUEST="UPLOAD_REQUEST";

export const GET_PUBLIC_DATA_REQUEST="GET_PUBLIC_DATA_REQUEST";
export const GET_PUBLIC_DATA_RESPONSE= "GET_PUBLIC_DATA_RESPONSE"